MDS-3484: DSRP Company Payment info admin UI to manage address change
bcgov/dormant-site-reclamation-program pull request #60
Opened 2021-03-26 00:23 UTC by jon-funk

2021-03-26 00:30 UTC, jon-funk commented
To test: 

`docker-compose up -d frontend`


navigate to `http://localhost:3000/review-company-payment-info`

Use the table to add/edit rows.

2021-03-26 16:07 UTC, jon-funk commented
Provided mock-up for scope:

![image-20210310-200445](https://user-images.githubusercontent.com/28266570/112660298-85c88a80-8e12-11eb-94a3-4e7bf2f497a6.png)

2021-03-26 17:00 UTC, exzizt commented on services/dsrp-api/app/api/company_payment_info/resources/company_payment_info.py
> +from datetime import datetime
Can we clean up these imports? I don't think they're all being used in this file.

2021-03-26 17:03 UTC, exzizt commented on services/dsrp-web/src/actionCreators/CPIActionCreator.js
> +export const fetchSelectedCompanyPaymentInfo = (params = {}) => (dispatch) => {
Can we remove this action creator and all references to it? It's not being used anywhere.

2021-03-26 17:06 UTC, exzizt commented on services/dsrp-web/src/actions/CPIActions.js
> +export const storeSelectedCompanyPaymentInfo = (payload) => ({
This can be removed too? Can we remove all the "selected" company payment info stuff?

2021-03-26 17:08 UTC, exzizt commented on services/dsrp-web/src/components/admin/ManageCompanyPaymentInfo.js
> +  sort_dir: "desc",
Default sort direction should be "asc" for company name.

2021-03-26 17:10 UTC, exzizt commented on services/dsrp-web/src/components/forms/AdminEditCompanyPaymentInfoForm.js
> +    this.autoSaveForm = setInterval(() => this.saveFormData(), 10000);
Don't think we need anything to do with form saving in this component.

2021-03-26 17:11 UTC, exzizt commented on services/dsrp-web/src/components/forms/AdminEditCompanyPaymentInfoForm.js
> +  shouldComponentUpdate = (nextProps, nextState) =>
This method and the receive props one below can both be deleted.

2021-03-26 17:11 UTC, exzizt commented on services/dsrp-web/src/components/forms/AdminEditCompanyPaymentInfoForm.js
> +  saveFormData() {
Everything to do with saving form data can be nuked in this file.

2021-03-26 17:14 UTC, exzizt commented on services/dsrp-web/src/components/modalContent/AdminEditCompanyPaymentInfoModal.js
> +      companyPaymentInfo={props.cpi}
Can we use the full name in all instances where you've used "CPI/cpi"?
cpi --> companyPaymentInfo

2021-03-26 17:14 UTC, exzizt commented on services/dsrp-web/src/components/pages/ReviewCompanyPaymentInfoPage.js
> +  state = {};
No need for all the empty stuff in this file :)

2021-03-26 17:15 UTC, exzizt commented on services/dsrp-web/src/constants/actionTypes.js
> +export const STORE_SELECTED_COMPANY_PAYMENT_INFO = "STORE_SELECTED_COMPANY_PAYMENT_INFO";
Don't forget to remove this when you remove everything to do with the "selected" company payment info.

2021-03-26 17:15 UTC, exzizt commented on services/dsrp-web/src/constants/routes.js
> +  route: "/review-company-payment-info",
Can we just call this route "company-payment-info"?

2021-03-26 17:16 UTC, exzizt commented on services/dsrp-web/src/reducers.js
> +import CPIReducerObject from "./reducers/CPIReducer";
Don't forget to refactor to companyPaymentInfoReducerObject when changing CPI --> companyPaymentInfo :)

2021-03-26 17:17 UTC, exzizt requested changes
Excellent work on this ticket! My comments are mostly to do with renaming/refactoring/tidying. Good job! :)

![image](https://user-images.githubusercontent.com/17113094/112669056-79e1c600-8e1c-11eb-81a1-a79b0d8012e1.png)

2021-03-29 15:54 UTC, jon-funk commented on services/dsrp-web/src/components/forms/AdminEditCompanyPaymentInfoForm.js
> +  saveFormData() {
I think it's from me misunderstanding some of the lifecycle hooks and a few cases of "I might need this later"

2021-03-29 17:47 UTC, exzizt commented on services/dsrp-web/src/components/modalContent/AdminEditCompanyPaymentInfoModal.js
> +const propTypes = {
Can you please define the prop types for this file?

2021-03-29 17:47 UTC, exzizt commented on services/dsrp-web/src/reducers.js
> +import CompanyPaymentInfoReducerObject from "./reducers/CompanyPaymentInfoReducer";
The casing here should be fixed as well

2021-03-29 17:47 UTC, exzizt commented on services/dsrp-web/src/reducers/CompanyPaymentInfoReducer.js
> +
Remove newline

2021-03-29 18:44 UTC, exzizt approved these changes
Great work on this feature Jonathan! The users are gonna be stoked and me too for not having to worry about manually doing these requests anymore! ❤️ 
Thank you!

2021-03-30 17:35 UTC, merged